"""create users table

Revision ID: 7b0d29e1c901
Revises: 
Create Date: 2026-03-11 16:54:57.695551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b0d29e1c901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detections')
    op.drop_table('reports')
    op.drop_table('report_status_logs')
    op.drop_table('admin_logs')
    op.drop_table('report_files')
    op.drop_table('role_requests')
    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('username'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('name')
        batch_op.drop_column('role')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
        batch_op.add_column(sa.Column('role', mysql.ENUM('user', 'admin', collation='utf8mb4_general_ci'), server_default=sa.text("'user'"), nullable=True))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('password')

    op.create_table('alerts',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('detection_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('alert_level', mysql.ENUM('낮음', '주의', '위험', '긴급'), nullable=True),
    sa.Column('message', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('read_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], name=op.f('alerts_ibfk_2')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('alerts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_requests',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('request_reason', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('status', mysql.ENUM('대기', '승인', '거절'), server_default=sa.text("'대기'"), nullable=True),
    sa.Column('reviewed_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('role_requests_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('role_requests_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('report_files',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('original_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('stored_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=False),
    sa.Column('file_type', mysql.ENUM('이미지', '영상'), nullable=False),
    sa.Column('file_size', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('report_files_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin_logs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('action_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('target_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('target_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('action_detail', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('admin_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('report_status_logs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('old_status', mysql.ENUM('접수', '확인중', '처리완료', '오탐'), nullable=True),
    sa.Column('new_status', mysql.ENUM('접수', '확인중', '처리완료', '오탐'), nullable=True),
    sa.Column('changed_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('memo', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('report_status_logs_ibfk_2')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('report_status_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reports',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=200), nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('report_type', mysql.ENUM('이미지', '영상', '카메라'), nullable=True),
    sa.Column('location_text', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('latitude', mysql.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', mysql.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('risk_level', mysql.ENUM('낮음', '주의', '위험', '긴급'), server_default=sa.text("'주의'"), nullable=True),
    sa.Column('status', mysql.ENUM('접수', '확인중', '처리완료', '오탐'), server_default=sa.text("'접수'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reports_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detections',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('file_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('detected_label', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('confidence', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('bbox_x1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bbox_y1', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bbox_x2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bbox_y2', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('detected_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['report_files.id'], name=op.f('detections_ibfk_2')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('detections_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
